name: Manual Build and Upload

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Create archive
        run: tar czf my-project.tar.gz my-project.tar.gz ./ pom.xml .github/workflows/build.yml --ignore-failed-read

      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: my-project.tar.gz
          path: my-project.tar.gz
